server:
  port: 5040
  servlet.context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:1032/vintrix-account-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 115874780761-m9j1qlb5u2s8q9664m3o9vt9hic3h61u.apps.googleusercontent.com
            client-secret: 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
  jpa:
     properties:
       hibernate:
         jdbc:
           time_zone: Asia/Kolkata
stripe:
  api:
    secret: sk_test_51TthQQ0G4WQm95GkuBEE2Js6cEVwc8vUhbaNYf26Ffw9ZTJWUJO4uHs7vvv45s8zjQk4AhCQKqnjrPStctAcr4Er00NSDuVX8f
  webhook:
    secret:  whsec_775c8e52cab4fa5f6a1ff970e6e52947b6b230848a88420f2769a622a79bf02f
client:
  url: http://localhost:8081
