server: 
  port: 8080

app:
  security:
    public-routes:
      - "/api/v1/account/auth/login"
      - "/api/v1/account/auth/signup
      - "/api/v1/account/webhooks/**
      - "/api/v1/workspace/public/**
      
spring:
  cloud:
    gateway.server.webflux:
      routes:
        #Account service(context-path:/account)
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account/**
          filters:
            - StripPrefix=2
            
        #Inteligence service(context-path:/account)
        - id: inteligence-service
          uri: lb://inteligence-service
          predicates:
            - Path=/api/v1/inteligence/**
          filters:
            - StripPrefix=2
            
        #workspace service(context-path:/account)
        - id: workspace-service
          uri: lb://workspace-service
          predicates:
            - Path=/api/v1/workspace/**
          filters:
            - StripPrefix=2
         
