server:
  port: 7040
  servlet.context-path: /inteligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:1032/vintrix-inteligence-db?TimeZone=Asia/Kolkata
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      enabled: false
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: llama3.2:3b
          temperature: 0.0   
---
spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://pgvector.vintrix-core.svc.clustor.local:5432/inteligence-db
    username: inteligence_user
    password: ${DB_PASSWORD} 
