server:
  port: 7040
  servlet.context-path: /inteligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:1032/vintrix-inteligence-db?TimeZone=Asia/Kolkata
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: llama3.2:3b
          temperature: 0.0   
