server:
  port: 9020
  servlet.context-path: /workspace

spring:
  datasource:
    url: jdbc:postgresql://localhost:9032/vintrix-workspace-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
